name: CI/CD Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Action rút code từ GitHub nhánh main xuống
      - name: Checkout code
        uses: actions/checkout@v3

      # Action tự động đăng nhập Docker Hub bằng token bạn đã lưu
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Action Build Docker Image từ Dockerfile và đẩy lên Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Đặt tên image là btdocker và gán 2 tag (latest và mã SHA của commit)
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/btdocker:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/btdocker:${{ github.sha }}
